### ISSUE TITLE
Warning at each start of the program on the presence of the tessdata subfolder

### ISSUE THREAD

**Issue by Blu3train** [buliasz/tesstrain-windows-gui#16]
I place the traineddata file in a training folder.
At each start, the notice appears that the tessdata subfolder is present inside selected tesseract folder.

![image](https://user-images.githubusercontent.com/80602322/190522764-f0d781bc-8c83-4281-9864-900f3fa0f3d5.png)

The warning is useful when selecting the Tesseract executables folder.
Is it possible to remove the check at startup?

**Comment by buliasz** [comment]
Fixed in the new version. Thanks for the report.
