### ISSUE TITLE
Ground-truth preview: "Recognized value" display problems

### ISSUE THREAD

**Issue by Blu3train** [buliasz/tesstrain-windows-gui#18]
Not a big deal but I still wanted to report it.
If the "Recognized value" text is longer than the window size, the text wraps but is covered by the "Value from .gt.txt file"
In the image you can see the blue pixels of the covered part of the characters.

![image](https://user-images.githubusercontent.com/80602322/190585180-f52b70c7-5f3d-47c2-928e-f37ca8506764.png)

**Comment by Blu3train** [comment]
I saw in the last release that you increased the spacing between the text. Thank you.
The addition of "space ignore" checkbox is excellent, especially for the Japanese language where Tesseract always adds a space to each character.

**Comment by buliasz** [comment]
Yes, I was going to ask if that helps because I've seen that Tesseract adds those spaces for unknown for me reason. Glad it does.
I've spend some time to improve the OCR preview. Please check out the newest version. It allows now to select/copy file path as well as recognition values. I've also implemented navigation forward/backward and stopping of the "Search for next wrong OCR" option. Any number of lines from results should be ok now too.

**Comment by Blu3train** [comment]
It's very good, thank you

**Comment by Blu3train** [comment]
Sorry, a clarification. When you press the "Find next Wrong OCR" button and change the name to "Stop searcing", the "Next" and "Previous" buttons will navigate between wrongs OCRs?

I ask you, because looking at the code it seems to me that to see the next wrong OCR I have to press stop and then press find next again...

**Comment by buliasz** [comment]
No, if you press the "Find next Wrong OCR" button it starts looking for the next picture which is wrongly OCRed. Once it finds it it stops there.
The "Previous" and "Next" buttons are just for manually navigating through the pictures one by one. But you gave me an idea I should just disable those while the automated search is in progress. Will do it.

**Comment by buliasz** [comment]
Oh, I see what you mean. In fact there's such bug. I'll fix it too. Thanks for letting me know!

**Comment by buliasz** [comment]
Done

**Comment by Blu3train** [comment]
About the "space ignore" checkbox, i found this thread.
https://github.com/tesseract-ocr/tessdata_fast/pull/7
It seems this configuration parameter has been added to eliminate the extra spaces for the languages chi_sim, kor, jpn and tha
**preserve_interword_spaces 1**

Here is an example of how to set the parameter
https://github.com/tesseract-ocr/tesseract/issues/991#issuecomment-311651758

So it would seem that instead of filtering the spaces, when flagging the checkbox this parameter should be added to the tesseract call
**-c preserve_interword_spaces=1**

**Comment by buliasz** [comment]
Thanks for finding it BTW

**Comment by Blu3train** [comment]
I report a curiosity that I discovered.
I was using the langdata files downloaded from github a couple of years ago and I noticed there were updates.

In the jpn.config file they added the instruction I had reported.
```
# Fix https://github.com/tesseract-ocr/tesseract/issues/988
preserve_interword_spaces 1
```

But is this file used by the training procedure if I put it in the tessdata folder?

**Comment by buliasz** [comment]
To be honest I have no idea. This GUI for Windows here is just using exactly the same procedures that are in official `tesstrain` shell script. You'd have to ask in [the main repo](https://github.com/tesseract-ocr/tesstrain) (forked by this one) if the training procedures / binaries use the .config file.
