### ISSUE TITLE
Training finishes immediately

### ISSUE THREAD

**Issue by WhosVenom** [buliasz/tesstrain-windows-gui#3]
Whenever I start training tesseract, after generating .lstm and .box files, the training cmd window pops up then immediately closes (sometimes without even launching a cmd window). 

It usually happens after training a few times.
I've already tried restarting tesstrain gui.

**Comment by buliasz** [comment]
Can you provide more details like version of the Tesseract you use and version of Windows?
Also it would be helpful if you enable the Debug mode and attach screenshots from each pop-up message.

**Comment by WhosVenom** [comment]
Windows version is 10.0.19043 and the Tesseract version is 5.0.1.20220118.
After running a training session with debug mode enabled, I have since discovered that the target error rate is met immediately.
Regardless, thanks for the assistance.
