### ISSUE TITLE
is this normal during training

### ISSUE THREAD

**Issue by ramdhan1989** [buliasz/tesstrain-windows-gui#34]
Hi, I would like to know if my training is successful?

![image](https://user-images.githubusercontent.com/41245856/200622388-6f1a6b77-bb98-4762-8357-392a74f9a60a.png)

 I am little bit confused because the cmd saying "press any keys to continue". I tried to press any keys but then the training progress disappeared.

thank you

**Comment by WhosVenom** [comment]
Try running it in debug mode and see what happens.

If you trained tesseract for long enough, it could close immediately because it can't learn anything new (I've had this "issue" myself).

**Comment by ramdhan1989** [comment]
Ok, it seems the training is running now since I have checkpoints file inside "data" folder.  After finishing the training process, what should I do next for inference? I am using jupyter notebook and calling tesseract like the image below :
![image](https://user-images.githubusercontent.com/41245856/200630412-52f45023-202f-487e-ae81-abd080338127.png)
do I need to click "create_exe" ? 
please advise
thank you

**Comment by Blu3train** [comment]
Before you train your own database, it is recommended to test with the ocrd-testset.zip
If the ocrd-testset.zip could be training successfully, it indicates that all the training tools on your computer are ready to use.

Make sure you have unzipped ocrd-testset.zip to ./data/foo-ground-truth folder before proceeding.

The ocrd-testset.zip archive can be found [here ](https://github.com/tesseract-ocr/tesstrain)

**Comment by ramdhan1989** [comment]
@Blu3train and @WhosVenom thanks a lot for your help. Yes, I am still testing using ocrd_testset. would you mind suggesting me about my previous question on what are the steps that must be taken after the training process?

**Comment by Blu3train** [comment]
Try attaching the tesstrain_gui.ini file so that we can see if you have configured the program correctly.
I don't know much, but at least someone can tell you if you have configured something wrong

**Comment by ramdhan1989** [comment]
> Try attaching the tesstrain_gui.ini file so that we can see if you have configured the program correctly. I don't know much, but at least someone can tell you if you have configured something wrong

please find the file below :
[https://drive.google.com/file/d/1DAE-SLWhE007hbkystgUHVFxMdKwi7Nw/view?usp=share_link](url)

thank you

**Comment by Blu3train** [comment]
link doesn't work to me

**Comment by ramdhan1989** [comment]
> (link doesn't work to me-) ok, copy the text work

Ok nice, looking forward to hearing from you

**Comment by Blu3train** [comment]
I don't know if what I write to you is essential for it to work, but this is what I impose and it works for me.

the GROUND_TRUTH_DIR set it to this folder
`GROUND_TRUTH_DIR=C:\Users\Owner\tesstrain-windows-gui-main\data\foo-ground-truth`

In the foo-ground-truth folder, unzip the contents of the ocrd-testset.zip file

As a start model try to use English and not German since the test data are made for the English language.

last thing, I put in the "data" folder also the files required by these parameters
WORDLIST_FILE=
NUMBERS_FILE=
PUNC_FILE=

I am attaching the files renamed from those of English
[foo.zip](https://github.com/buliasz/tesstrain-windows-gui/files/9963907/foo.zip)

**Comment by ramdhan1989** [comment]
> 



> I don't know if what I write to you is essential for it to work, but this is what sets and works for me.
> 
> the GROUND_TRUTH_DIR set it to this folder `GROUND_TRUTH_DIR=C:\Users\Owner\tesstrain-windows-gui-main\data\foo-ground-truth`
> 
> In the foo-ground-truth folder, unzip the contents of the ocrd-testset.zip file
> 
> As a start model try to use English and not German since the test data are made for the English language.
> 
> last thing, I put in the "data" folder also the files required by these parameters WORDLIST_FILE= NUMBERS_FILE= PUNC_FILE=
> 
> I am attaching the files renamed from those of English [foo.zip](https://github.com/buliasz/tesstrain-windows-gui/files/9963907/foo.zip)

thanks a lot. After the training, what is next? do you have example of doing inference?

**Comment by Blu3train** [comment]
You take the new model, in this case foo.traineddata, and use it with tesseract instead of the original model.

**Comment by ramdhan1989** [comment]
I am trying to use my own data. But I got this error 
![image](https://user-images.githubusercontent.com/41245856/200878532-606b0892-33bc-45d1-b1ae-4f9ff94360e5.png)
how to solve the problem easily? instead of removing the error image.

**Comment by Blu3train** [comment]
why psm 8?

**Comment by ramdhan1989** [comment]
> why psm 8?

because my image contains one word. I tried also using 13 but the error was same. 
please advice

**Comment by Blu3train** [comment]
The image must be in TIFF format and the suffix can be .tif/.png/.bin.png/.nrm.png.
The name of the text file is the same as the image name, the content is the text corresponding to the
image, and the suffix is named .gt.txt.
Both the image and the corresponding text are **required to be a single line of text**.

**Comment by ramdhan1989** [comment]
what does this error mean?
![image](https://user-images.githubusercontent.com/41245856/200899737-3e3dbf46-2351-48a9-9189-86b4a3e2b5a1.png)

**Comment by ramdhan1989** [comment]
Hi @Blu3train , I tried again but still got the error like this
`Bad box coordinates in boxfile string! Far Carbon/Oxygen RatioVolumePerPressure (m3/Pa)AreaPerTime (ft2/h)Uncorrected Attenuation ResistivityDimensionless (bbl/bbl)flowlengthPressurePerLength (bar/m)Area (bbl/ft)MassPerLengthPerTime (kg/m.a)Time (0.5 ms)AreaPerTime (mm2/s)Analog 12Dimensionless (ppdk)MassPerTime (kg/s)Carbon/Oxygen Ratio UncertaintyArea (bbl/ft)Velocity (m/s)Sigma Borehole CorrectedInverseTemperature (1/degF)Velocity (ft/s)Far IC Capture Oxygen Activation Relative YieldMassPerAreaPerTime (MPa.s/m)
Extracting unicharset from plain text file C:\Users\Owner\tesstrain-windows-gui-main\data\text\all-gt
Other case Z of z is not in unicharset
Wrote unicharset file C:\Users\Owner\tesstrain-windows-gui-main\data\text\my.unicharset`

I tried to continue but then show this error message 
`Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica
Page 1` 
similar to my previous post

please advise

**Comment by buliasz** [comment]
Hi, thank you @Blu3train for helping. I want to let you know guys I have a lot personal stuff recently, but once I have a bit more time I'll be more able to help.
@ramdhan1989 can you share which version of Tesseract you have installed? I know that some versions of Tesseract binaries display particular communicates on StdErr instead of StdOut, but everything work good anyway. Overall different Tesseract builds behave quite differently in some occasions. 
On the other hand the "0 dpi" communicate suggest that the Leptonica library cannot properly process your images. If you can maybe you may share one image so that we could test it locally to see if we can reproduce the error.

**Comment by ramdhan1989** [comment]
Hi @buliasz , this is the version
![image](https://user-images.githubusercontent.com/41245856/201257748-a2258c2c-6391-4c5c-8302-c9be23dfd8ee.png)

please find the image on the link below :  
[https://drive.google.com/drive/folders/1oEMhPZB_OimM0T2TGJ8eiVmLZxPBtvBj?usp=share_link](url)

thanks

**Comment by buliasz** [comment]
Just tested locally it works without problems, [here's output of the learning stage](justpaste.it/2lu9z).
Can you try installing 5.2 version from https://github.com/UB-Mannheim/tesseract/wiki and check if it works. I guess the issue is with the compilation you use.

**Comment by buliasz** [comment]
BTW this is not really related to the GUI itself so you may also want to ask about it in [the main tesstrain repository](https://github.com/tesseract-ocr/tesstrain). Just send executed command (you can copy it in the GUI debug mode) and the unexpected output. You can also try to execute the command in your shell, but the output should be the same.

**Comment by ramdhan1989** [comment]
@buliasz I tried to use from here [https://github.com/UB-Mannheim/tesseract/wiki](url)
The error is gone now. However, during .box and .lstmf generation, this window always pop up for each image
![image](https://user-images.githubusercontent.com/41245856/202836328-df8d8b59-f4f7-4127-923e-ea0fc6efeba5.png)
So, I need to click "ok" for each image. is it normal? or is there something that can be set to solve it?

**Comment by Blu3train** [comment]
Uncheck the Debug option

**Comment by ramdhan1989** [comment]
thanks it is running now. 
![image](https://user-images.githubusercontent.com/41245856/202844589-d61d6a33-3d59-4aca-9c3c-40c18e3bbb91.png)
is this normal?

**Comment by buliasz** [comment]
Never seen it before. If you search for it on the Internet there are some discussions about it. You'll have to check that. Seems related to tesstrain, not the GUI itself.
