### ISSUE TITLE
tesstrain_gui.ahk freezing 

### ISSUE THREAD

**Issue by KBearMan** [buliasz/tesstrain-windows-gui#39]
Trying to get this setup and train some data, but when I run tesstrain_gui.ahk, it freezes at the last setup step of "Verifying/installing required Python modules". I'm not entirely sure why it's freezing but it seems no matter how long I leave it, it always happens.

**Comment by buliasz** [comment]
Try executing this command in your cmd and see what will be the result:
```
python -m pip install Pillow>=6.2.1 python-bidi>=0.4 matplotlib pandas
```

**Comment by KBearMan** [comment]
python -m pip install "Pillow>=6.2.1" "python-bidi>=0.4" "matplotlib" "pandas"
Requirement already satisfied: Pillow>=6.2.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (10.0.1)
Requirement already satisfied: python-bidi>=0.4 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (0.4.2)            
Requirement already satisfied: matplotlib in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (3.8.0)                  
Requirement already satisfied: pandas in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (2.1.1)                      
Requirement already satisfied: six in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from python-bidi>=0.4) (1.16.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (23.1)      
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (3.1.1)    
Requirement already satisfied: numpy<2,>=1.21 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (1.26.0)     
Requirement already satisfied: cycler>=0.10 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (0.11.0)       
Requirement already satisfied: fonttools>=4.22.0 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (4.42.1)  
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (1.4.5)   
Requirement already satisfied: contourpy>=1.0.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from matplotlib) (1.1.1)    
Requirement already satisfied: tzdata>=2022.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\...\tesstrain-windows-gui-main\venv\lib\site-packages (from pandas) (2023.3.post1)
WARNING: You are using pip version 21.1.2; however, version 23.2.1 is available.
You should consider upgrading via the 'C:\Users\...\tesstrain-windows-gui-main\venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by buliasz** [comment]
Looks fine. Can you try pulling the current version I've just uploaded and see if that helps?

**Comment by KBearMan** [comment]
I tried re-downloading the latest version and unfortunately it still seems to be stuck on the 3rd part of startup. 
For reference I have Python 3.11.5 installed, at least that's what I see when I run python from command prompt.

**Comment by buliasz** [comment]
This is strange. Which version of Windows do you use?

**Comment by KBearMan** [comment]
Windows 10

**Comment by buliasz** [comment]
Hmm... the fact that the execution got to the "Verifying/installing required Python modules" means that the script positively verified the python version. 

Moreover shell command execution was fine (this app executes "python --version" to verify it).
Now it's very strange that it gets stuck on the "Verifying/installing required Python modules" stage, especially that if there were any errors then the script would show it.

There's only one reason that I can think of is that the python's pip asks for some confirmation and waits for input which it would never get obviously. I have added `--no-input --no-pip-version-check` options to the command executed by script. Please check if the new version works for you.

BTW I'm testing it on both Windows 10 and 11, should work for you too, let's find out what's going on.

**Comment by buliasz** [comment]
@KBearMan I have good news. I've managed to reproduce the issue and fixed it. It seems that in some conditions (not sure what they really are) execution of python `pip` installer is freezing if not on visible console (I guess Windows OS related issue). 
I have made the command to execute on visible console and it fixed the issue. 
Just pushed fixed version, hopefully it will work for you too. Let me know.

**Comment by zdrave08** [comment]
Hi, I try to start training with your test data but have errors. Please take a look on image that I attach. Also the same error I get when I try with my data.
<img width="949" alt="UntitledTesseract" src="https://github.com/buliasz/tesstrain-windows-gui/assets/13600860/92227edb-7155-45a5-824f-c57c485f3ff7">

**Comment by buliasz** [comment]
> Hi, I try to start training with your test data but have errors. Please take a look on image that I attach. Also the same error I get when I try with my data. <img alt="UntitledTesseract" width="949" src="https://private-user-images.githubusercontent.com/13600860/314437499-92227edb-7155-45a5-824f-c57c485f3ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzY1MDcsIm5iZiI6MTcxMDk3NjIwNywicGF0aCI6Ii8xMzYwMDg2MC8zMTQ0Mzc0OTktOTIyMjdlZGItNzE1NS00NWE1LTgyNGYtYzU3YzQ4NWYzZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIzMTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjY5YTcwMGRjMTQ4MzA0YWNhZjEzYjg2Y2FlOTI5OGZlZDk5NGY0OWU4ZTgxZTliOGRlNDE5MDJiOTZhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bazS_SzKG5u9bjteUCK-86xT61Y-YJXPK-z5GC3pkSc">

It's unrelated to this topic. Moved to a new issue.
