### ISSUE TITLE
SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by buliasz** [buliasz/tesstrain-windows-gui#41]
Hi, I try to start training with your test data but have errors. Please take a look on image that I attach. Also the same error I get when I try with my data.
<img width="949" alt="UntitledTesseract" src="https://github.com/buliasz/tesstrain-windows-gui/assets/13600860/92227edb-7155-45a5-824f-c57c485f3ff7">

_Originally posted by @zdrave08 in https://github.com/buliasz/tesstrain-windows-gui/issues/39#issuecomment-2009086839_

**Comment by buliasz** [comment]
@zdrave08 I've just pushed a fix. Please check and let me know if that works for you.

**Comment by zdrave08** [comment]
Hi, it's works but now there is new problem and not sure is about script that creates ground truth or is from your side. Maybe you can help? This is error that I get
 C:\Users\Zdravko Lukic\Downloads\tesseract_tutorial-main\tesstrain\data\eng\srp_latn\srp_erste.lstm is an integer (fast) model, cannot continue training
Failed to continue from: C:\Users\Zdravko Lukic\Downloads\tesseract_tutorial-main\tesstrain\data\eng\srp_latn\srp_erste.lstm

**Comment by buliasz** [comment]
Looks like you've used the optional "Start model" option. If you click help for it (the question mark button on the right side of the option), you'll get description which explains your issue:
"Model to use as a starting one and continue from it. Model files are the ones with '.traineddata' extension in your 'TessData folder'. **Only 'best' tessdata file version can be used for it. Please check Tesseract User Manual section 'Traineddata Files' for details**.
[Here's my answer](https://github.com/buliasz/tesstrain-windows-gui/issues/2#issuecomment-1070314691) to another question about the same issue. You'll find there links with details.
