### ISSUE TITLE
Window output is not sizeable making it impossible to see all the output

### ISSUE THREAD

**Issue by quaesitor-scientiam** [buliasz/tesstrain-windows-gui#6]
![Screenshot 2022-04-15 094518](https://user-images.githubusercontent.com/60949191/163578352-b2ec5caa-7107-4350-b72c-f71fb559ba27.png)

**Comment by buliasz** [comment]
This is not related to GUI so unfortunately you would need to report it [on the original Tesstrain](https://github.com/tesseract-ocr/tesstrain) project. This fork is only to introduce Windows GUI.

**Comment by buliasz** [comment]
Fixed in the newest 4.2 version. Thanks for reporting.
